#!/usr/bin/env python

from __future__ import print_function

import sys
import xmltodict, json

# See http://stackoverflow.com/a/10231610/541202

def main():
    # json.dump(xmltodict.parse(sys.stdin), sys.stdout)
    # json.dump(xmltodict.parse(sys.stdin), sys.stdout, sort_keys=True, indent=2)
    json.dump(xmltodict.parse(sys.stdin), sys.stdout, indent=2)
    print()

if __name__ == "__main__":
  main()
