#!/usr/bin/env python

from __future__ import print_function

import json
import sys
import yaml

def main():
    json.dump(yaml.safe_load(sys.stdin), sys.stdout)
    print()

if __name__ == "__main__":
  main()
